In [14]:
import torch
pe = torch.zeros(10, 5)
pe

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [15]:
position = torch.arange(0, 10).unsqueeze(1)
position

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [16]:
import math
div_term = torch.exp(torch.arange(0, 5, 2) * -(math.log(10000.0) / 5))
div_term

tensor([1.0000e+00, 2.5119e-02, 6.3096e-04])

In [18]:
torch.exp(torch.arange(0,10,2))

tensor([1.0000e+00, 7.3891e+00, 5.4598e+01, 4.0343e+02, 2.9810e+03])

In [ ]:
div_term = torch.exp(torch.arange(0, d_model, 2) * -(math.log(10000.0) / d_model))